# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e57197e201a6a82ae80cde6994ae496c0e4d3342f5b064818c88aeecee6dd066ed7143f5361786c816bee81ad4b4e7dce9153ff1a6122775e11aa58c51c8ace

test:
  secret_key_base: 272f26520743916f297854dd4c76fe5416427f2bfd9f21a5bd49c61189fa59ad8c98647a94f2095c25ce2fdd25201c05805aff20e812a85d03b5fac66e27dbb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
